'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpiceMaster.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;h2&gt;
        '''    English&lt;/h2&gt;
        '''&lt;p&gt;
        '''    This guide is a &lt;b&gt;per food category&lt;/b&gt; classification of spices and herbs. It 
        '''    will help you find what you can combine with the food you want to cook.&lt;/p&gt;
        '''&lt;p&gt;
        '''    &lt;b&gt;Comments&lt;/b&gt; on a spice are in regard to the specific food category or 
        '''    explain further the type of food. The &amp;#39;+&amp;#39; symbol in some comments means that you 
        '''    can use that spice at the current food category, as well as in the subcategory 
        '''    that it is mentionoed.&lt;/p&gt;
        '''&lt;p&gt;
        '''    Many foods [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property html_prologue() As String
            Get
                Return ResourceManager.GetString("html_prologue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to function checkExpand() {
        '''    ToggleVisibility(event.srcElement.id);
        '''};
        '''function ToggleVisibility(id) {
        '''    if (&quot;&quot; != id) {
        '''        var elOut = document.all[id];
        '''        var elIn = document.all[id + &quot;_&quot;];
        '''        if (null != elIn) {
        '''            if (elIn.style.display == &quot;none&quot;) {
        '''                elIn.style.display = &quot;&quot;;
        '''                elOut.innerText = &quot;-&quot;;
        '''            }
        '''            else {
        '''                elIn.style.display = &quot;none&quot;;
        '''                elOut.innerText = &quot;+&quot;;
        '''            }
        '''      [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property html_script() As String
            Get
                Return ResourceManager.GetString("html_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Greek books:&lt;ul&gt;
        '''&lt;li&gt;Νίκος Δ. Πλατής - Μπαχαρικό λεξικό, εκδ. Κέδρος, 2003
        '''&lt;li&gt;Αλέξανδρος Γιώτης – Μπαχαρικά και βότανα στην κουζίνα, εκδ. Les Livres du Tourisme, 2005
        '''&lt;li&gt;Anne Iburg – Λεξικό για μπαχαρικά, εκδ. Τζιάμπρης Πυραμίδα, 2006
        '''&lt;li&gt;Βαγγέλης Δρίσκας – Αρωματική Κουζίνα, εκδ. Πατάκη, 2004
        '''&lt;/ul&gt;&lt;br&gt;
        '''Also:&lt;ul&gt;
        '''&lt;li&gt;περιοδ. Gourmet, ειδική έκδοση του περιοδ. ΕΨΙΛΟΝ, Κυριακάτικη Ελευθεροτυπία, διάφορα τεύχη
        '''&lt;li&gt;Μυρσίνη Λαμπράκη – Τα χόρτα, εκδ. ελληνικά γράμματα, 1997, 2000
        '''&lt;/ul&gt;&lt;br&gt;
        '''Internet so [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property html_sources() As String
            Get
                Return ResourceManager.GetString("html_sources", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to h3
        '''{
        '''	font-weight: bold;
        '''	font-size: larger;
        '''	color: yellow;
        '''	background-color: #9999ff;
        '''	padding: 2px;
        '''	margin: 2px;
        '''	border: yellow thin ridge;
        '''}
        '''
        '''dl {margin: 5px 0px 0px 0px;}
        '''
        '''dd
        '''{
        '''	margin: 0px 0px 2px 0px;
        '''
        '''	border-radius: 0px 0px 10px 10px;
        '''	padding-left: 10px;
        '''	border-top: 0px;
        '''	border: yellow thin ridge;
        '''}
        '''
        '''dt
        '''{
        '''	font-weight: bold;
        '''	color: white;
        '''	background-color: gold;
        '''	padding: 2px;
        '''	border: yellow thin ridge;
        '''	border-radius: 10px 10px 0px 0px;
        '''}
        '''dt.l1 {color: Blue [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property html_style() As String
            Get
                Return ResourceManager.GetString("html_style", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property ICON_APPLICATION() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_APPLICATION", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_APPLICATION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_APPLICATION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_BROWSE_BACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_BROWSE_BACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_BROWSE_FORWARD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_BROWSE_FORWARD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_BROWSE_GO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_BROWSE_GO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_BROWSE_REFRESH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_BROWSE_REFRESH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_BROWSE_UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_BROWSE_UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_FOODS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_FOODS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_CLEAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_CLEAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_CUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_CUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_EDIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_EDIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_PASTE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_PASTE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_LIST_REMOVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_LIST_REMOVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property IMAGE_SPICES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMAGE_SPICES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;MUIXML Language=&quot;English&quot; Version=&quot;1&quot; LanguageName=&quot;English&quot;&gt;
        '''  &lt;General&gt;
        '''    &lt;ItemsCaptions&gt;
        '''      &lt;Spice Text=&quot;Spice&quot; /&gt;
        '''    &lt;/ItemsCaptions&gt;
        '''    &lt;ListHeaders&gt;
        '''      &lt;Name Text=&quot;Name&quot; /&gt;
        '''      &lt;FullName Text=&quot;Full Name&quot; /&gt;
        '''      &lt;Abbrevation Text=&quot;Abbrevation&quot; /&gt;
        '''      &lt;Comments Text=&quot;Comments&quot; /&gt;
        '''      &lt;CommentText Text=&quot;Comment&quot; /&gt;
        '''      &lt;CommentScope Text=&quot;Scope&quot; /&gt;
        '''    &lt;/ListHeaders&gt;
        '''    &lt;ListCaptions&gt;
        '''      &lt;Spices Text=&quot;Spices&quot; /&gt;
        '''      &lt;Foods Text=&quot;Foods&quot; /&gt;
        '''      &lt;Combinations Tex [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MUI_en() As String
            Get
                Return ResourceManager.GetString("MUI_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;MUIXML Language=&quot;Greek&quot; Version=&quot;1&quot; LanguageName=&quot;Ελληνικά&quot;&gt;
        '''  &lt;General&gt;
        '''    &lt;ItemsCaptions&gt;
        '''      &lt;Spice Text=&quot;Μπαχαρικό&quot; /&gt;
        '''    &lt;/ItemsCaptions&gt;
        '''    &lt;ListHeaders&gt;
        '''      &lt;Name Text=&quot;Όνομα&quot; /&gt;
        '''      &lt;FullName Text=&quot;Πλήρες Όνομα&quot; /&gt;
        '''      &lt;Abbrevation Text=&quot;Συντ.&quot; /&gt;
        '''      &lt;Comments Text=&quot;Σχόλια&quot; /&gt;
        '''      &lt;CommentText Text=&quot;Σχόλιο&quot; /&gt;
        '''      &lt;CommentScope Text=&quot;Αναφορά&quot; /&gt;
        '''    &lt;/ListHeaders&gt;
        '''    &lt;ListCaptions&gt;
        '''      &lt;Spices Text=&quot;Μπαχαρικά&quot; /&gt;
        '''      &lt;Foods Text=&quot;Φαγητά&quot; /&gt;
        '''      &lt;Combinations [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MUI_gr() As String
            Get
                Return ResourceManager.GetString("MUI_gr", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property NewDocumentHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocumentHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property OpenFileHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property OptionsHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property saveHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property SPICE_MASTER_DOCUMENT() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SPICE_MASTER_DOCUMENT", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
